### PR TITLE
Return instances of Coord instead of Coord3d in Bresenham::line2D. Th…

### PR DESCRIPTION
**Pull request by smelc**
…at's less surprising for callers that call methods like 'Collection::contains(Object)' on the result or pours the result into a Collection<Coord>

### CODE REVIEW

**Comment by smelc** [comment]
I've added the main commit later on, see "Implement TextPanel in ..."

**Comment by tommyettinger** [comment]
Great! It's interesting that surprising behavior hadn't come up sooner. Thanks for busting the unused code in ZoneDemo! I'm curious to see how the variable-width font looks, but I'll need to make a variable-width distance field font so it can zoom (thankfully, those are much easier to make than a fixed-width distance field font). If you're looking for a serif font, that term refers to typefaces like Times New Roman (variable-width serif) as opposed to Arial (variable-width sans-serif), where serifs are the perpendicular decorations added onto the main lines of most letters. Fixed-width fonts often are in a weird middle ground where `i` usually has a serif on the bottom and top-left of the main line (to make the width of the char larger), but `T` usually doesn't. I'm probably going to make a distance field font out of Gentium, which is an Open Font License-d variable-width serif font that is meant to look good in print and at high zoom levels, but also supports a lot of languages.

Merging!

**Comment by tommyettinger** [comment]
And I just noticed the scrolling, yay! This is great stuff.

**Comment by tommyettinger** [comment]
There's some issues with this relating to resizing the window; I'll try to fix the issue on my end but I just committed a partial addition so you can see (and so distance field fonts work). 

It should look like:

image

When maximized to approx. 1080p, I pressed '?' then resized to the original window size, producing a background glitch:

image

And when I took that screenshot, after returning to the window it looked... strange:

image

Any ideas? I (probably incorrectly) implemented a resize() method in TextPanel, that just calls initialize() with the existing text and a new width/height. It doesn't seem to do what I would expect, often pushing things around on the screen and *shrinking* the black background area when a *larger* height is passed.

**Pull request merged**
