### PR TITLE
Add ICombinedPanel.GroupImpl, an implementation of ICombinedPanel bac…

### PR DESCRIPTION
**Pull request by smelc**
…ked up by libgdx's group. It can compute its size after being constructed, which I use to display the rogue's inventory, after setting its content. Ideally, we should add an example I think within EverythingDemo; but I did not have the resource to do it yet.

I've also deleted some warnings about missing @Override and deleted a reference to HashMap.Entry which is java 8-visible only.

### CODE REVIEW

**Comment by tommyettinger** [comment]
I'm fairly sure this either won't or shouldn't build; at least, if a test or demo for ICombinedPanel.GroupImpl was written in squidlib-util's examples, it would show the problem. The squidlib-util module has no dependency on libgdx, so a shared interface for things that don't necessarily rely on libgdx can't use a Group, but that doesn't appear as a problem if you only use GroupImpl from squidlib-gdx (libgdx will already be on the classpath, and squidlib-gdx can import it in -util without issue, but code that strictly uses -util without using libgdx won't be able to). I'll merge this because the rest of the changes look excellent, but I need to move GroupImpl to squidlib-gdx for now, which will soon become squidlib when AWT is removed.

**Comment by tommyettinger** [comment]
Merged and moved the inner class that used libgdx to squidlib-gdx. IntelliJ complained as soon as I merged, it refused to build while the dependency couldn't be met.

**Comment by smelc** [comment]
Ahh sorry my bad, I'm still using Eclipse now and I have SquidLib as a single project; hence it compiles if I put libgdx-dependent stuff in squidlib-util. I should change that!

I see that you removed the generic type of colors (`T` -> libgdx's Color), but that breaks my game because I instantiate `T` with my own subtype of libgdx's Color. I think that the generic parameter is nice, because it really puts no burden on a "classic" client that will instantiate it with libgdx's Color, but offers more flexibility for others.

I can put the generic type back in a later PR as I'll anyway need to change it locally, and I know I'll do another PR later on (maybe tomorrow, otherwise next week).

Thanks for merging :+1:

**Comment by tommyettinger** [comment]
I'm still not totally clear on how generics work in this case, but I can easily make the changes in the next few hours along with the grass in dungeons issue, #91 . Should GroupCombinedPanel have a type parameter `<T extends Color>` where Color is libGDX's Color, or just `<T>` ?

**Comment by smelc** [comment]
I had simply `T` in my code, because I didn't need more; but I guess from a library's POV, it's better to have `T extends Color`, because, as the class is ultimately backed by SquidPanel, you can't really have an instance where `T` wouldn't be a subtype of `Color` (also that's because we'll remove the awt implementation).

**Pull request merged**
