### PR TITLE
Add KissSpill, a variant of Spill with a light API + détail in IColor…

### PR DESCRIPTION
**Pull request by smelc**
…edString

### CODE REVIEW

**Comment by SquidPony** [comment]
maybe this should be called Splash

**Comment by smelc** [comment]
Splash is indeed a hip name :-)

**Comment by tommyettinger** [comment]
This is good! It could probably be made into a single static method that would keep less state lying around. I'm definitely merging this, but I think KissSpill (in part due to the acronym being all-caps, KISS, and the class name being capitalized like the non-acronym word, Kiss) sounds less like a simple implementation of Spill and more like a Valentine's Day salivary mishap. I could rename it to SimpleSpill or Splash, and I'm leaning toward Splash, unless people agree that having "SimpleThing" variants on existing classes would be a good convention. I'll add a static method that takes the impassable chars as an argument, and make the existing method just call that, giving it the impassable set that the existing API deals with. The only difference with the existing API would be the class name change.

I think having some more simple variants like this could be useful. I have a simple, non-random floodfill in DijkstraMap (but it might use the larger DijkstraMap API in some ways), and a sort-of-simpler static non-random floodfill in CoordPacker (operating on the packed data for floors, usually, so checking for walls is as simple as checking for whether a cell is 'on' in the data). Having a nice and simple random floodfill (spill) is a good addition.

**Comment by SquidPony** [comment]
I'm opposed to having NewThing type names largely because it doesn't give
good information for new users and gets really awkward later if other bits
change.

**Comment by tommyettinger** [comment]
Splash it is, then.

**Comment by smelc** [comment]
@tommyettinger> I think it's better to keep it an object (I mean: to have a static method call the object is OK, but not the other way around), because the state is a single `Set<Character>` which is typically of size 1 ^^ so that's lightweight. Having an object is handful for clients (that can override methods if they want).

**Comment by tommyettinger** [comment]
Good point, though that would require a singleton object, and static objects with state are... weird on Android (they may have their state persist between application runs). I guess since the object's so lightweight anyway, it isn't a problem.

**Comment by smelc** [comment]
Nah if you want a static entry point, I'd make it create a fresh Splash every time. Not all objects are evil :-) Users won't go crazy on calling this API anyway.

Btw I must say I wrote this, because the water generator of `DungeonGenerator` was creating too many pools. It looks very good for grass, because it puts small patches there and there, but that wasn't good for water :-/ (for example it would never generate such pools: https://twitter.com/hgamesdev/status/692310541998637057 (10% fill thrice)).

**Pull request merged**
