### PR TITLE
Performance test case for #73

### PR DESCRIPTION
**Pull request by davidbecker**
I created a testcase for #73 to check the implications of the change

### CODE REVIEW

**Comment by tommyettinger** [comment]
Good good, I'm curious about the results on lower-end hardware as you mentioned in #73 . All the imports this uses are also (thankfully) present on Android so @devilbuddy may be able to test since s/he seems to have a working setup for Android dev involving SquidLib. Merging! (I'll make the tiniest refactor to fix the typo in the class name, heh.)

**Comment by davidbecker** [comment]
I am currently running the test against the head version, and have a dataset for c050ca617 to compare. I will report back when the test is done :smile:

**Comment by tommyettinger** [comment]
I suspect there may be an infinite loop in the test as written, by the way. I have no idea if all the LOS and FOV methods behave correctly when started in a wall at the edge of the map, and that may be why RippleFOV with VERY_LOOSE specified caused the exception. It's still using all the CPU I can give it as well as as much RAM as it can hoard. A RAM bottleneck may be preventing my test from being accurate, too, but I think 100 simultaneous repeated runs of the most challenging algorithms in the library are, heh, hard for computers to compute. :anguished:

**Comment by davidbecker** [comment]
You are probably right. I started the test with 5*10 rounds and compared the mean times. I noticed that the computing time of the old implementation was faster at the beginning and ramped up over time. But now that the second test is done, it is time for some number crunshing and comparing :smiley:

**Comment by tommyettinger** [comment]
Wow, less than 10 minutes for me with 8 threads and the slight changes to only start the loops at 1 instead of 0, make end DIMENSION - 2 to avoid starting in walls, and end the loops sooner accordingly.
```
invoking 100 tasks on 8 threads
42368
41715
40849
41425
41325
41518
41058
41204
40330
40196
40370
40280
40131
40559
40761
41880
40109
40319
40060
40195
40258
40807
40567
41368
40059
40553
40374
40333
40305
40713
40944
41823
40075
40472
40508
40403
40281
40846
40771
41437
39909
40536
40452
40449
40351
40577
40991
41847
40420
40690
40707
40657
40662
40762
40899
41775
40194
40609
40881
40395
40564
40817
41033
41718
39971
40192
40801
40527
40330
40640
40905
41784
39854
40738
40559
40956
40544
40877
40904
41757
40707
41001
40896
41106
40850
41285
41227
41908
40602
41089
41096
41247
41028
40951
40670
37920
25958
23695
23423
23193
```
I thought it was going to take longer based off of how much RAM it wanted (and couldn't get more in the first run. It _wasn't_ starved of RAM on this run).

**Pull request merged**
